### ISSUE TITLE
Plugin still stops to respond

### ISSUE THREAD

**Issue by solbadguy2010** [valiquette/homebridge-easee#6]
Hi, since your last fix your plugin is running stable through internet connectin losses. nevertheless i am still experiencing the problem, that every 1-2 days the plugin stops responding and do not reflect the state of the charger or react to inputs in the home app. I have not yet seen any log activity, but i will monitore more with an eye on it. reboot of HB helps.

Have you experienced anything like this? Maybe easee disconnecting every 24h or something?

**Comment by valiquette** [comment]
The token used for the API that sends commands expires ever 24 hours, and the plugin will try and refresh it every 23 hours. This I have tested. 
The same token is uses to establish the signalR connections for live updates. I am not doing anything special to refresh that. It is possible that I do need to drop and re establish that connect every 24 hours too. 
I do not have any real way yo test this, but if you think this is what is going on, I can get you a beta to try.

**Comment by solbadguy2010** [comment]
Sure, i can test whatever you like. Maybe its an idea to do the refresh every 12 hours, to be sure?

**Comment by solbadguy2010** [comment]
Ok, i observed further. Today tje plugin was running without error. Reported changes like „charging started“, „finished“ and „disconnected“ (see screenshots). Afterwarts there are absolutely no log entries but now the charger is not reacting to a „lock“ command anymore und the plugin does not reflect a connected cable. Its like it simply looses the connection to the server and does not re-establish it.

![CFA0FA4F-6C81-406F-95F0-CEC9D4452C70](https://user-images.githubusercontent.com/30244171/160929036-2d86fdbf-4d45-47ab-a4f4-52d199169376.png)
![898BE490-1ED9-4A8C-B516-98A13AB38674](https://user-images.githubusercontent.com/30244171/160929039-f4a9a3ff-97b3-451e-a84e-edf78d319001.jpeg)

**Comment by solbadguy2010** [comment]
I now rebooted homebride and all is working again.

![16B927E2-8FEF-4856-8C0C-4B3B54CA07F8](https://user-images.githubusercontent.com/30244171/160929758-1d573400-a4d8-4e04-b99c-d2a323e815f6.jpeg)

**Comment by valiquette** [comment]
You description points to an expired token, after looking at this I has typo in a key line. This would have caused the plugin to stop 24 hours after loading. 
I do not have the ability to test but pretty sure this is fixed, you should see a message in the log 23 hours after you restart it. if you can control things after 24 hours then it is fixed. I do not believe the web socket for updates back to the plugin will expire.
v1.1.8 is published. please let me know if tis resolves the issue.

**Comment by solbadguy2010** [comment]
Great you found the error :-)
 Just installed the update and restarted HB. In 24h we know more.

**Comment by solbadguy2010** [comment]
Something is still wrong. 24h passed and the plugin is not responding anymore.

**Comment by solbadguy2010** [comment]
After another 48h it is working now. Will have a look in the future, but looks good by now.
